name: minio
description: Unofficial MinIO Dart Client SDK that provides simple APIs to access any Amazon S3 compatible object storage server.
version: 3.5.0
homepage: https://github.com/xtyxtyx/minio-dart
issue_tracker: https://github.com/xtyxtyx/minio-dart/issues

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  meta: ^1.15.0
  http: ^1.2.1
  crypto: ^3.0.3
  convert: ^3.1.1
  xml: ^6.5.0
  buffer: ^1.2.3
  intl: ^0.18.1
  mime: ^1.0.5
  path: ^1.9.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  html: ^0.15.4
